# Generated by Django 4.1.6 on 2023-02-20 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimAgroAssurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OffreuAssurance', models.CharField(max_length=300)),
                ('TypeAssurance', models.CharField(max_length=300)),
                ('CulturAssure', models.CharField(max_length=300)),
                ('NivPrime', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DimAgroCommercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProdVenteSpecul', models.CharField(max_length=300)),
                ('TypeVente', models.CharField(max_length=300)),
                ('MarchRegroupement', models.CharField(max_length=300)),
                ('ClientAgro', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DimAgroCulture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ZonProd_Cult', models.CharField(max_length=300)),
                ('Cultur_Pratique', models.CharField(max_length=300)),
                ('Type_Semence', models.CharField(max_length=300)),
                ('Type_Culture_Pratique', models.CharField(max_length=250)),
                ('VarieteCultive', models.CharField(max_length=250)),
                ('SourcApprovisIntran', models.CharField(max_length=300)),
                ('SourcApprovisSemenc', models.CharField(max_length=300)),
                ('SourcApprovisEngrProdPhyto', models.CharField(max_length=300)),
                ('SourcApprovisMatAgro', models.CharField(max_length=300)),
                ('TypeAcquisIntran', models.CharField(max_length=300)),
                ('TypeAcquisMat', models.CharField(max_length=300)),
                ('TypeFertilisUtil', models.CharField(max_length=300)),
                ('TypePesticidUtil', models.CharField(max_length=300)),
                ('ModAcquisParcel', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='DimAgroFinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OffreServicFinance', models.CharField(max_length=300)),
                ('DemandApport', models.CharField(max_length=250)),
                ('TypeGaranExige', models.CharField(max_length=300)),
                ('LongProcedCredi', models.IntegerField()),
                ('DelaiRembourse', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DimAgroOrganisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_Organisation', models.CharField(max_length=300)),
                ('TypeServicOfferOP', models.CharField(max_length=300)),
                ('BesoinForm', models.CharField(max_length=300)),
                ('ContrainGlobalAgro', models.CharField(max_length=300)),
                ('ContrainMajFilier', models.CharField(max_length=300)),
                ('InfrasStockCondition', models.CharField(max_length=300)),
                ('FournisEmballag', models.CharField(max_length=300)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DimAgroProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_Production', models.CharField(max_length=300)),
                ('CodeCulture', models.IntegerField()),
                ('type_cult_prat', models.CharField(max_length=250)),
                ('RendemHectarCult', models.IntegerField()),
                ('TauxPertPostRecoltParCult', models.IntegerField()),
                ('TypeSolExist', models.CharField(max_length=300)),
                ('TypeDegradZonCultur', models.CharField(max_length=300)),
                ('CauseDegrad', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='MultiStepFormModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('twitter', models.CharField(max_length=255)),
                ('facebook', models.CharField(max_length=255)),
                ('gplus', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FactAgriculture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ZonProd_Cult', models.CharField(max_length=300)),
                ('SupMoyDetenuMenag', models.IntegerField()),
                ('NbrSouscript', models.IntegerField()),
                ('PrixVentMoySaison', models.IntegerField()),
                ('MontMoyTypeCultur', models.IntegerField()),
                ('TauxInteret', models.IntegerField()),
                ('SupMaxDetenu', models.IntegerField()),
                ('SupMinDetenu', models.IntegerField()),
                ('SupMoyDetenu', models.IntegerField()),
                ('SupMoyEmblave', models.IntegerField()),
                ('RendemHectarCult', models.IntegerField()),
                ('TauxPertPostRecoltParCult', models.IntegerField()),
                ('IdProduction_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='das.dimagroproduction')),
                ('idagroassurance_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='das.dimagroassurance')),
                ('idagrofinance_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='das.dimagrofinance')),
                ('idculture_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='das.dimagroculture')),
                ('idorganisation_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='das.dimagroorganisation')),
                ('numagrocommercial_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='das.dimagrocommercial')),
            ],
        ),
    ]
