# Generated by Django 4.1.6 on 2023-04-05 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
    ]
